{
 "title": "test dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "test panel 001",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) *100",
     "legendFormat": "idle"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[1m])) * 100",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "quantile and avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "avg(jmeter_latency_summary)", "legendFormat": "quantile avg" },
    { "expr": "jmeter_latency_summary", "legendFormat": "quantile {{quantile}}" }
   ]
  },
  { "title": "test row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}